// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyfqugbpvafdaiekswyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5ZnF1Z2JwdmFmZGFpZWtzd3lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDUwMTMsImV4cCI6MjA3MTAyMTAxM30.PyCpNsjyiQIg5BUik7I96gfCex4TNyOPfud3S2E-E04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});